### ISSUE TITLE
speedups fail to compile on Python 2.7

### ISSUE THREAD

**Issue by felixonmars** [simplejson/simplejson#193]
This is a new error in 3.12.1 and still present in 3.13.0:

```
building 'simplejson._speedups' extension
gcc -pthread -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python2.7 -c simplejson/_speedups.c -o build/temp.linux-x86_64-2.7/simplejson/_speedups.o
In file included from /usr/include/python2.7/Python.h:80:0,
                 from simplejson/_speedups.c:2:
simplejson/_speedups.c: In function ‘encoder_encode_string’:
simplejson/_speedups.c:2824:27: error: ‘unicode’ undeclared (first use in this function); did you mean ‘encoded’?
         !JSON_ASCII_Check(unicode) &&
                           ^
```
